name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? What would the user experience look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI / Commands
        - HCL Parsing
        - Provider Protocol (gRPC)
        - State Management
        - DAG / Parallelism
        - Plan / Apply Output
        - YAML Config
        - Documentation
        - Other
    validations:
      required: true
